# Generated by Django 4.2.6 on 2023-10-12 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='name1',
        ),
    ]
