# Generated by Django 4.2.6 on 2023-10-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0006_rename_desc1_team_desc_rename_img1_team_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc',
            new_name='desc1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='name1',
        ),
    ]
