# Generated by Django 4.2.6 on 2023-10-13 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0007_rename_desc_team_desc1_rename_img_team_img1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='desc1',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='img1',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name1',
            new_name='name',
        ),
    ]
